# Note: This file is meant for use on my server with nginx-proxy set up
version: '3'

services:
  website:
    build: .
    environment:
      - VIRTUAL_HOST=seabury.life

networks:
  default:
    external:
      name: draven_default
