# Note: This file is meant for use on my server with nginx-proxy set up
version: '3'

services:
  website:
    build: .
    environment:
      - VIRTUAL_HOST=seabury.life
      - MONGOOSE_URI=mongodb+srv://draven:sNIsOk5iJxCmlQtf@cluster0-yccmv.mongodb.net/seabury-suggestions?retryWrites=true&w=majority

networks:
  default:
    external:
      name: draven_default
